### ISSUE TITLE
Cannot call .type in transformations

### ISSUE THREAD

**Issue by markusvoelter** [slisson/shadowmodels#164]
Sascha suspects generator ordering issue.

**Comment by slisson** [comment]
Running the typesystem on the node adapters of the transformation engine doesn't work. We need to materialise the "transient model" and run the typesystem on that.
Making this incremental is another problem. You can't just invoke the typesystem from a transformation, because it would create to many dependencies.
We have to incrementally update the materialised transient model so that the typesystem can run incrementally, but we all know how good the incremental typesystem is (you have to press F5 all the time). A full rerun of the typesystem is probably the only reliable solution.
